import { useCallback, useEffect, useMemo, useState } from "react";
import { createApi } from "@smart-thapho/web-core/api";
import { EmptyState, ErrorNotice, LoadingState, Modal, PageHead, StatusBadge, formatMoney, formatNumber, toDateInput } from "../components/ui.jsx";

function RateForm({ onCancel, onSubmit, saving }) {
  const submit = (event) => { event.preventDefault(); const value = Object.fromEntries(new FormData(event.currentTarget).entries()); onSubmit({ rateName: value.rateName, amount: Number(value.amount), billingCycle: value.billingCycle, isActive: true }); };
  return <form className="waste-form" onSubmit={submit}><label className="waste-form__wide">ชื่ออัตราค่าบริการ<input name="rateName" required placeholder="เช่น ค่าบริการเก็บขยะครัวเรือน" /></label><label>จำนวนเงิน (บาท)<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>รอบค่าบริการ<select name="billingCycle" defaultValue="MONTHLY"><option value="MONTHLY">รายเดือน</option><option value="QUARTERLY">รายไตรมาส</option><option value="YEARLY">รายปี</option></select></label><footer><button type="button" className="waste-button waste-button--secondary" onClick={onCancel}>ยกเลิก</button><button className="waste-button waste-button--primary" disabled={saving}>{saving ? "กำลังบันทึก" : "เพิ่มอัตราค่าบริการ"}</button></footer></form>;
}

function ChargeForm({ users, rates, onCancel, onSubmit, saving }) {
  const [amount, setAmount] = useState(""); const period = toDateInput().slice(0, 8) + "01";
  const submit = (event) => { event.preventDefault(); const value = Object.fromEntries(new FormData(event.currentTarget).entries()); onSubmit({ serviceUserId: value.serviceUserId, feeRateId: value.feeRateId || null, billingPeriod: value.billingPeriod, dueDate: value.dueDate, amount: Number(value.amount) }); };
  return <form className="waste-form" onSubmit={submit}><label className="waste-form__wide">ผู้ใช้บริการ<select name="serviceUserId" required defaultValue=""><option value="" disabled>เลือกผู้ใช้บริการ</option>{users.filter((user) => user.isActive).map((user) => <option key={user.id} value={user.id}>{user.serviceNo} — {user.fullName} (หมู่ {user.villageNo})</option>)}</select></label><label>อัตราค่าบริการ<select name="feeRateId" defaultValue="" onChange={(event) => { const rate = rates.find((item) => item.id === event.target.value); if (rate) setAmount(String(rate.amount)); }}><option value="">กำหนดยอดเอง</option>{rates.filter((rate) => rate.isActive).map((rate) => <option key={rate.id} value={rate.id}>{rate.rateName} — {formatMoney(rate.amount)}</option>)}</select></label><label>ยอดค่าบริการ<input name="amount" type="number" min="0.01" step="0.01" required value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>รอบค่าบริการ<input name="billingPeriod" type="date" required defaultValue={period} /></label><label>กำหนดชำระ<input name="dueDate" type="date" required defaultValue={toDateInput()} /></label><footer><button type="button" className="waste-button waste-button--secondary" onClick={onCancel}>ยกเลิก</button><button className="waste-button waste-button--primary" disabled={saving}>{saving ? "กำลังบันทึก" : "สร้างรายการค่าบริการ"}</button></footer></form>;
}

export default function BillingPage({ token }) {
  const api = useMemo(() => createApi(token), [token]);
  const [charges, setCharges] = useState([]); const [rates, setRates] = useState([]); const [users, setUsers] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [modal, setModal] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [nextCharges, nextRates, nextUsers] = await Promise.all([api.get("/api/waste/charges"), api.get("/api/waste/fee-rates"), api.get("/api/waste/service-users")]); setCharges(nextCharges); setRates(nextRates); setUsers(nextUsers); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, [api]);
  useEffect(() => { void load(); }, [load]);
  const create = async (path, input) => { setSaving(true); setError(""); try { await api.post(path, input); setModal(""); await load(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const updateCharge = async (charge, status) => { setSaving(true); setError(""); try { await api.patch(`/api/waste/charges/${charge.id}`, { status }); await load(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const totalPending = charges.filter((charge) => ["PENDING", "OVERDUE"].includes(charge.status)).reduce((sum, charge) => sum + Number(charge.amount), 0);
  return <>
    <PageHead eyebrow="BILLING" title="ค่าบริการเก็บขยะ" detail="กำหนดอัตรา บันทึกรอบค่าบริการ และตรวจสอบสถานะการชำระ" actions={<><button type="button" className="waste-button waste-button--secondary" onClick={() => setModal("rate")}>จัดการอัตราค่าบริการ</button><button type="button" className="waste-button waste-button--primary" onClick={() => setModal("charge")}>+ สร้างรายการค่าบริการ</button></>} />
    <ErrorNotice error={error} onRetry={load} />
    <section className="waste-billing-summary"><article><span>รายการค่าบริการทั้งหมด</span><strong>{formatNumber(charges.length)}</strong><small>รายการ</small></article><article><span>ยอดรอชำระและค้างชำระ</span><strong>{formatMoney(totalPending)}</strong><small>จากข้อมูลที่บันทึกในระบบ</small></article><article><span>อัตราค่าบริการที่เปิดใช้</span><strong>{formatNumber(rates.filter((rate) => rate.isActive).length)}</strong><small>อัตรา</small></article></section>
    <section className="waste-panel"><header className="waste-panel__head"><div><p>SERVICE CHARGES</p><h2>รายการค่าบริการ</h2></div><span>การแจ้งเตือนผ่าน LINE จะเชื่อมในขั้นตอนช่องทางประชาชน</span></header>{loading ? <LoadingState /> : !charges.length ? <EmptyState title="ยังไม่มีรายการค่าบริการ" detail="สร้างรายการจากทะเบียนผู้ใช้บริการและอัตราค่าบริการที่กำหนด" actionLabel="สร้างรายการค่าบริการ" onAction={() => setModal("charge")} /> : <div className="waste-table-wrap"><table className="waste-table"><thead><tr><th>ผู้ใช้บริการ</th><th>รอบค่าบริการ</th><th>กำหนดชำระ</th><th>ยอด</th><th>สถานะ</th><th /></tr></thead><tbody>{charges.map((charge) => <tr key={charge.id}><td><strong>{charge.serviceNo}</strong><small>{charge.fullName} · บ้าน {charge.houseNo}</small></td><td>{charge.billingPeriod}</td><td>{charge.dueDate}</td><td><strong>{formatMoney(charge.amount)}</strong><small>{charge.rateName || "กำหนดยอดเอง"}</small></td><td><StatusBadge value={charge.status} /></td><td>{["PENDING", "OVERDUE"].includes(charge.status) ? <button type="button" className="waste-table-action" disabled={saving} onClick={() => updateCharge(charge, "PAID")}>บันทึกชำระแล้ว</button> : null}</td></tr>)}</tbody></table></div>}</section>
    {modal === "rate" ? <Modal title="เพิ่มอัตราค่าบริการเก็บขยะ" onClose={() => setModal("")}><RateForm onCancel={() => setModal("")} onSubmit={(input) => create("/api/waste/fee-rates", input)} saving={saving} /></Modal> : null}
    {modal === "charge" ? <Modal title="สร้างรายการค่าบริการ" onClose={() => setModal("")}><ChargeForm users={users} rates={rates} onCancel={() => setModal("")} onSubmit={(input) => create("/api/waste/charges", input)} saving={saving} /></Modal> : null}
  </>;
}
