import { useCallback, useEffect, useMemo, useState } from "react";
import { createApi } from "@smart-thapho/web-core/api";
import { EmptyState, ErrorNotice, LoadingState, Modal, PageHead, StatusBadge, formatDate, formatNumber, toDateInput } from "../components/ui.jsx";

function toIso(date, time) { return time ? new Date(`${date}T${time}:00+07:00`).toISOString() : null; }

function PlanForm({ resources, date, onCancel, onSubmit, saving }) {
  const [scheduledDate, setScheduledDate] = useState(date);
  const defaultPlanNo = `WST-${scheduledDate.replaceAll("-", "")}-001`;
  const submit = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const value = Object.fromEntries(form.entries()); onSubmit({ planNo: value.planNo, scheduledDate, routeId: value.routeId, vehicleId: value.vehicleId, driverId: value.driverId, scheduledStartAt: toIso(scheduledDate, value.scheduledStartAt), scheduledEndAt: toIso(scheduledDate, value.scheduledEndAt), note: value.note || null }); };
  return <form className="waste-form" onSubmit={submit}><label>เลขที่แผนปฏิบัติงาน<input name="planNo" required defaultValue={defaultPlanNo} /></label><label>วันที่ปฏิบัติงาน<input type="date" value={scheduledDate} onChange={(event) => setScheduledDate(event.target.value)} required /></label><label>เส้นทางเก็บขยะ<select name="routeId" required defaultValue=""><option value="" disabled>เลือกเส้นทาง</option>{resources.routes.filter((item) => item.isActive).map((item) => <option value={item.id} key={item.id}>{item.routeCode} — {item.routeName}</option>)}</select></label><label>รถเก็บขยะ<select name="vehicleId" required defaultValue=""><option value="" disabled>เลือกรถเก็บขยะ</option>{resources.vehicles.filter((item) => item.status !== "OUT_OF_SERVICE").map((item) => <option value={item.id} key={item.id}>{item.vehicleCode} — {item.registrationNo}</option>)}</select></label><label>คนขับรถเก็บขยะ<select name="driverId" required defaultValue=""><option value="" disabled>เลือกคนขับรถเก็บขยะ</option>{resources.drivers.filter((item) => item.isActive).map((item) => <option value={item.id} key={item.id}>{item.fullName}</option>)}</select></label><label>เวลาเริ่มตามแผน<input name="scheduledStartAt" type="time" /></label><label>เวลาสิ้นสุดตามแผน<input name="scheduledEndAt" type="time" /></label><label className="waste-form__wide">หมายเหตุ<textarea name="note" rows="3" placeholder="ข้อสั่งการหรือรายละเอียดงาน" /></label><footer><button type="button" className="waste-button waste-button--secondary" onClick={onCancel}>ยกเลิก</button><button className="waste-button waste-button--primary" disabled={saving}>{saving ? "กำลังบันทึก" : "สร้างแผนปฏิบัติงาน"}</button></footer></form>;
}

export default function PlansPage({ token, navigate }) {
  const api = useMemo(() => createApi(token), [token]);
  const [date, setDate] = useState(toDateInput()); const [plans, setPlans] = useState([]); const [resources, setResources] = useState({ vehicles: [], drivers: [], routes: [] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [createOpen, setCreateOpen] = useState(false); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [nextPlans, vehicles, drivers, routes] = await Promise.all([api.get(`/api/waste/plans?date=${date}`), api.get("/api/waste/vehicles"), api.get("/api/waste/drivers"), api.get("/api/waste/routes")]); setPlans(nextPlans); setResources({ vehicles, drivers, routes }); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, [api, date]);
  useEffect(() => { void load(); }, [load]);
  const createPlan = async (input) => { setSaving(true); setError(""); try { await api.post("/api/waste/plans", input); setCreateOpen(false); await load(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const updateStatus = async (id, status) => { setSaving(true); setError(""); try { await api.patch(`/api/waste/plans/${id}/status`, { status }); await load(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  return <>
    <PageHead eyebrow="OPERATION PLANNING" title="แผนปฏิบัติงานเก็บขยะ" detail="มอบหมายเส้นทาง รถเก็บขยะ และคนขับก่อนเริ่มปฏิบัติงาน" actions={<><label className="waste-date-field"><span>วันที่ปฏิบัติงาน</span><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><button type="button" className="waste-button waste-button--primary" onClick={() => setCreateOpen(true)}>+ สร้างแผนงาน</button></>} />
    <ErrorNotice error={error} onRetry={load} />
    <section className="waste-panel">{loading ? <LoadingState /> : !plans.length ? <EmptyState title="ยังไม่มีแผนปฏิบัติงาน" detail="เริ่มจากจัดเตรียมรถ คนขับ และเส้นทาง แล้วสร้างแผนงานสำหรับวันที่เลือก" actionLabel="สร้างแผนปฏิบัติงาน" onAction={() => setCreateOpen(true)} /> : <div className="waste-plan-list">{plans.map((plan) => <article key={plan.id}><div className="waste-plan-list__date"><strong>{formatDate(plan.scheduledDate, { day: "numeric" })}</strong><span>{formatDate(plan.scheduledDate, { month: "short" })}</span></div><div className="waste-plan-list__main"><header><div><small>{plan.planNo}</small><h2>{plan.routeName}</h2></div><StatusBadge value={plan.status} /></header><dl><div><dt>รถเก็บขยะ</dt><dd>{plan.vehicleCode}</dd></div><div><dt>คนขับ</dt><dd>{plan.driverName}</dd></div><div><dt>จุดเก็บ</dt><dd>{formatNumber(plan.collectedStops)} / {formatNumber(plan.stopTotal)} จุด</dd></div><div><dt>เวลา</dt><dd>{plan.scheduledStartAt ? formatDate(plan.scheduledStartAt, { hour: "2-digit", minute: "2-digit" }) : "ไม่ระบุ"}</dd></div></dl></div><div className="waste-plan-list__actions">{plan.status === "SCHEDULED" ? <button type="button" className="waste-button waste-button--primary" disabled={saving} onClick={() => updateStatus(plan.id, "IN_PROGRESS")}>เริ่มปฏิบัติงาน</button> : null}{plan.status === "IN_PROGRESS" || plan.status === "INTERRUPTED" ? <><button type="button" className="waste-button waste-button--secondary" onClick={() => navigate(`tracking?plan=${plan.id}`)}>ติดตาม</button><button type="button" className="waste-button waste-button--primary" disabled={saving} onClick={() => updateStatus(plan.id, "COMPLETED")}>บันทึกเสร็จสิ้น</button></> : null}{plan.status === "SCHEDULED" ? <button type="button" className="waste-button waste-button--quiet" disabled={saving} onClick={() => updateStatus(plan.id, "CANCELLED")}>ยกเลิก</button> : null}</div></article>)}</div>}</section>
    {createOpen ? <Modal title="สร้างแผนปฏิบัติงานเก็บขยะ" onClose={() => setCreateOpen(false)}><PlanForm resources={resources} date={date} onCancel={() => setCreateOpen(false)} onSubmit={createPlan} saving={saving} /></Modal> : null}
  </>;
}
