import { useCallback, useEffect, useMemo, useState } from "react";
import { createWasteApplication } from "../composition-root/createWasteApplication.js";
import { EmptyState, ErrorNotice, LoadingState, PageHead, StatusBadge, formatMoney, formatNumber, toDateInput } from "../components/ui.jsx";
import { wasteReportPolicy } from "../domain/WasteReportPolicy.js";

export default function ReportsPage({ token }) {
  const api = useMemo(() => createWasteApplication(token), [token]);
  const [from, setFrom] = useState(toDateInput(new Date(new Date().getFullYear(), new Date().getMonth(), 1))); const [to, setTo] = useState(toDateInput()); const [operations, setOperations] = useState([]); const [billing, setBilling] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [nextOperations, nextBilling] = await Promise.all([api.get(`/api/waste/reports/operations?from=${from}&to=${to}`), api.get("/api/waste/reports/billing")]); setOperations(nextOperations); setBilling(nextBilling); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, [api, from, to]);
  useEffect(() => { void load(); }, [load]);
  const summary = useMemo(() => wasteReportPolicy.summarize(operations), [operations]);
  return <>
    <PageHead eyebrow="OPERATIONS REPORTS" title="รายงานการปฏิบัติงานเก็บขยะและค่าบริการ" detail="สรุปข้อมูลจากแผนปฏิบัติงานเก็บขยะ ค่าบริการ และประวัติที่บันทึกจริงในระบบ" actions={<div className="waste-report-range"><label>ตั้งแต่<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>ถึง<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><button type="button" className="waste-button waste-button--secondary" onClick={() => void load()}>รีเฟรช</button></div>} />
    <ErrorNotice error={error} onRetry={load} />
    {loading ? <LoadingState /> : <>
      <section className="waste-kpis waste-kpis--reports"><article><span>แผนปฏิบัติงานเก็บขยะ</span><strong>{formatNumber(summary.totalPlans)}</strong><small>แผน</small></article><article><span>เสร็จสิ้น</span><strong>{formatNumber(summary.completedPlans)}</strong><small>แผน</small></article><article><span>จุดเก็บที่ยืนยันแล้ว</span><strong>{formatNumber(summary.collectedStops)}</strong><small>จาก {formatNumber(summary.totalStops)} จุด</small></article><article><span>ความครบถ้วน</span><strong>{summary.completionPercent === null ? "-" : `${summary.completionPercent}%`}</strong><small>ตามจุดที่กำหนด</small></article></section>
      <section className="waste-panel"><header className="waste-panel__head"><div><p>OPERATIONS</p><h2>รายงานแผนปฏิบัติงานเก็บขยะ</h2></div></header>{operations.length ? <div className="waste-table-wrap"><table className="waste-table"><thead><tr><th>วันปฏิบัติงาน</th><th>แผนปฏิบัติงานเก็บขยะ / เส้นทาง</th><th>รถ / พนักงานประจำรถขยะ</th><th>จุดเก็บ</th><th>สถานะ</th></tr></thead><tbody>{operations.map((item) => <tr key={item.planNo}><td>{item.scheduledDate}</td><td><strong>{item.planNo}</strong><small>{item.routeName}</small></td><td><strong>{item.vehicleCode}</strong><small>{item.driverName}</small></td><td>{formatNumber(item.collectedStops)} / {formatNumber(item.stopTotal)} จุด</td><td><StatusBadge value={item.status} /></td></tr>)}</tbody></table></div> : <EmptyState title="ยังไม่มีข้อมูลแผนปฏิบัติงานเก็บขยะในช่วงที่เลือก" detail="รายงานจะเริ่มแสดงเมื่อมีการสร้างแผนปฏิบัติงานเก็บขยะ" />}</section>
      <section className="waste-panel"><header className="waste-panel__head"><div><p>BILLING</p><h2>สรุปค่าบริการตามรอบ</h2></div></header>{billing.length ? <div className="waste-table-wrap"><table className="waste-table"><thead><tr><th>รอบค่าบริการ</th><th>สถานะ</th><th>จำนวนรายการ</th><th>ยอดรวม</th></tr></thead><tbody>{billing.map((item, index) => <tr key={`${item.billingPeriod}-${item.status}-${index}`}><td>{item.billingPeriod}</td><td><StatusBadge value={item.status} /></td><td>{formatNumber(item.count)}</td><td><strong>{formatMoney(item.amount)}</strong></td></tr>)}</tbody></table></div> : <EmptyState title="ยังไม่มีข้อมูลค่าบริการ" detail="ข้อมูลจะปรากฏเมื่อเจ้าหน้าที่สร้างรายการค่าบริการให้ผู้ใช้บริการ" />}</section>
    </>}
  </>;
}
