import { useCallback, useEffect, useMemo, useState } from "react";
import { createApi } from "@smart-thapho/web-core/api";
import { EmptyState, ErrorNotice, LoadingState, Modal, PageHead, StatusBadge, formatNumber } from "../components/ui.jsx";

function ServiceUserForm({ initial, villages, routes, onCancel, onSubmit, saving }) {
  const submit = (event) => { event.preventDefault(); const value = Object.fromEntries(new FormData(event.currentTarget).entries()); onSubmit({ serviceNo: value.serviceNo, fullName: value.fullName, phone: value.phone, houseNo: value.houseNo, villageId: Number(value.villageId), addressDetail: value.addressDetail || null, lineUserId: value.lineUserId || null, routeId: value.routeId || null, latitude: value.latitude ? Number(value.latitude) : null, longitude: value.longitude ? Number(value.longitude) : null, isActive: value.isActive === "true" }); };
  return <form className="waste-form" onSubmit={submit}><label>เลขผู้ใช้บริการ<input name="serviceNo" required defaultValue={initial?.serviceNo || ""} placeholder="เช่น WU-0001" /></label><label>ชื่อผู้ใช้บริการ<input name="fullName" required defaultValue={initial?.fullName || ""} /></label><label>โทรศัพท์<input name="phone" inputMode="numeric" pattern="0[0-9]{9}" required defaultValue={initial?.phone || ""} /></label><label>บ้านเลขที่<input name="houseNo" required defaultValue={initial?.houseNo || ""} /></label><label>หมู่บ้าน<select name="villageId" required defaultValue={initial?.villageId || ""}><option value="" disabled>เลือกหมู่บ้าน</option>{villages.map((village) => <option key={village.id} value={village.id}>หมู่ {village.villageNo} {village.name}</option>)}</select></label><label>เส้นทางรับผิดชอบ<select name="routeId" defaultValue={initial?.routeId || ""}><option value="">ยังไม่กำหนด</option>{routes.filter((route) => route.isActive).map((route) => <option key={route.id} value={route.id}>{route.routeCode} — {route.routeName}</option>)}</select></label><label>ละติจูด<input name="latitude" type="number" step="any" defaultValue={initial?.latitude || ""} /></label><label>ลองจิจูด<input name="longitude" type="number" step="any" defaultValue={initial?.longitude || ""} /></label><label className="waste-form__wide">รายละเอียดที่อยู่<textarea name="addressDetail" defaultValue={initial?.addressDetail || ""} rows="2" /></label><label className="waste-form__wide">LINE User ID <small>ระบบจะบันทึกจากการลงทะเบียนผ่าน LINE เมื่อเชื่อมขั้นตอนบริการประชาชน</small><input name="lineUserId" defaultValue={initial?.lineUserId || ""} /></label><label>สถานะ<select name="isActive" defaultValue={String(initial?.isActive ?? true)}><option value="true">รับบริการอยู่</option><option value="false">ปิดบริการ</option></select></label><footer><button type="button" className="waste-button waste-button--secondary" onClick={onCancel}>ยกเลิก</button><button className="waste-button waste-button--primary" disabled={saving}>{saving ? "กำลังบันทึก" : initial ? "บันทึกการแก้ไข" : "เพิ่มผู้ใช้บริการ"}</button></footer></form>;
}

export default function ServiceUsersPage({ token }) {
  const api = useMemo(() => createApi(token), [token]);
  const [users, setUsers] = useState([]); const [routes, setRoutes] = useState([]); const [villages, setVillages] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [modal, setModal] = useState(null); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [nextUsers, nextRoutes, nextVillages] = await Promise.all([api.get("/api/waste/service-users"), api.get("/api/waste/routes"), api.get("/api/public/villages")]); setUsers(nextUsers); setRoutes(nextRoutes); setVillages(nextVillages); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, [api]);
  useEffect(() => { void load(); }, [load]);
  const save = async (input) => { setSaving(true); setError(""); try { if (modal?.id) await api.patch(`/api/waste/service-users/${modal.id}`, input); else await api.post("/api/waste/service-users", input); setModal(null); await load(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  return <>
    <PageHead eyebrow="SERVICE USERS" title="ทะเบียนผู้ใช้บริการเก็บขยะ" detail="จัดการบ้านเรือนหรือสถานที่รับบริการ และกำหนดเส้นทางที่รับผิดชอบ" actions={<button type="button" className="waste-button waste-button--primary" onClick={() => setModal({})}>+ เพิ่มผู้ใช้บริการ</button>} />
    <ErrorNotice error={error} onRetry={load} />
    <section className="waste-panel"><header className="waste-panel__head"><div><p>REGISTERED SERVICE USERS</p><h2>ผู้ใช้บริการทั้งหมด</h2></div><span>{formatNumber(users.length)} ราย</span></header>{loading ? <LoadingState /> : !users.length ? <EmptyState title="ยังไม่มีทะเบียนผู้ใช้บริการ" detail="เพิ่มบ้านเรือนหรือสถานที่เพื่อกำหนดเส้นทางเก็บขยะและออกค่าบริการ" actionLabel="เพิ่มผู้ใช้บริการ" onAction={() => setModal({})} /> : <div className="waste-table-wrap"><table className="waste-table"><thead><tr><th>เลขผู้ใช้บริการ</th><th>ผู้ใช้บริการ / ติดต่อ</th><th>ที่อยู่</th><th>เส้นทาง</th><th>LINE</th><th>สถานะ</th><th /></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{user.serviceNo}</strong></td><td><strong>{user.fullName}</strong><small>{user.phone}</small></td><td>หมู่ {user.villageNo} · {user.houseNo}<small>{user.villageName}</small></td><td>{user.routeName || "ยังไม่กำหนด"}</td><td>{user.lineUserId ? "เชื่อมแล้ว" : "ยังไม่เชื่อม"}</td><td><StatusBadge value={user.isActive ? "AVAILABLE" : "OUT_OF_SERVICE"} /></td><td><button type="button" className="waste-table-action" onClick={() => setModal(user)}>แก้ไข</button></td></tr>)}</tbody></table></div>}</section>
    {modal ? <Modal title={modal.id ? "แก้ไขผู้ใช้บริการเก็บขยะ" : "เพิ่มผู้ใช้บริการเก็บขยะ"} onClose={() => setModal(null)}><ServiceUserForm initial={modal.id ? modal : null} villages={villages} routes={routes} onCancel={() => setModal(null)} onSubmit={save} saving={saving} /></Modal> : null}
  </>;
}
