import { useEffect, useMemo, useState } from "react";
import { createApi } from "../lib/api.js";
import DashboardMap from "../components/DashboardMap.jsx";

const initialStats={total:0,dogs:0,cats:0,pending:0,vaccinations:0,sterilizations:0,openCases:0};
const statusLabel={SUBMITTED:["รอตรวจสอบ","amber"],UNDER_REVIEW:["กำลังตรวจ","blue"],NEED_MORE_INFO:["ขอข้อมูลเพิ่ม","rose"],APPROVED:["อนุมัติแล้ว","green"],REJECTED:["ไม่อนุมัติ","gray"]};

function StatCard({tone,icon,label,value,detail}){return <article className={`stat ${tone}`}><div className="stat-icon">{icon}</div><div><p>{label}</p><strong>{Number(value||0).toLocaleString("th-TH")}</strong><small>{detail}</small></div></article>}
function Progress({label,value,color}){return <div className="progress"><div><b>{label}</b><strong>{value}%</strong></div><span><i className={color} style={{width:`${value}%`}}/></span></div>}
function VillageBars({rows=[]}){const data=rows.length?rows.map(r=>({villageNo:r.villageNo,value:Number(r.totalPets)?Math.round(Number(r.vaccinated)*100/Number(r.totalPets)):0})):Array.from({length:11},(_,i)=>({villageNo:i+1,value:0}));return <div className="villages">{data.map(item=><div key={item.villageNo}><span>หมู่ {item.villageNo}</span><i><b style={{height:`${item.value}%`}}/></i><strong>{item.value}%</strong></div>)}</div>}
function RequestTable({requests=[]}){return <div className="table-wrap"><table><thead><tr><th>เลขที่คำขอ</th><th>เจ้าของ / สัตว์</th><th>พื้นที่</th><th>สถานะ</th><th>วันที่ยื่น</th><th/></tr></thead><tbody>{requests.slice(0,6).map(r=>{const s=statusLabel[r.status]||[r.status||"-","gray"];return <tr key={r.id||r.referenceNo}><td><b>{r.referenceNo}</b></td><td><div className="pet-cell"><i>{r.species==="DOG"?"ส":"ม"}</i><span><b>{r.petName}</b><small>{r.ownerName}</small></span></div></td><td>หมู่ {r.villageNo}</td><td><span className={`badge ${s[1]}`}>{s[0]}</span></td><td>{r.submittedAt?new Date(r.submittedAt).toLocaleDateString("th-TH",{day:"numeric",month:"short"}):"-"}</td><td><button className="row-action">›</button></td></tr>})}</tbody></table></div>}

export default function DashboardPage({token,navigate}){
  const api=useMemo(()=>createApi(token),[token]);const[stats,setStats]=useState(initialStats);const[requests,setRequests]=useState([]);const[villages,setVillages]=useState([]);const[mapItems,setMapItems]=useState([]);const[live,setLive]=useState(false);
  useEffect(()=>{let active=true;Promise.all([api.get("/api/admin/dashboard"),api.get("/api/admin/registrations"),api.get("/api/admin/reports/villages"),api.get("/api/admin/map")]).then(([a,b,c,d])=>{if(!active)return;setStats(a&&typeof a==="object"&&!Array.isArray(a)?a:initialStats);setRequests(Array.isArray(b)?b:[]);setVillages(Array.isArray(c)?c:[]);setMapItems(Array.isArray(d)?d:[]);setLive(true)}).catch(()=>active&&setLive(false));return()=>{active=false}},[api]);
  const total=Number(stats.total||0),vaccinationCoverage=total?Math.round(Number(stats.vaccinations||0)*100/total):0,sterilizationCoverage=total?Math.round(Number(stats.sterilizations||0)*100/total):0;
  return <><section className="welcome"><div><p className="eyebrow">ภาพรวมระบบ · ปี 2569</p><h1>สวัสดีครับ เจ้าหน้าที่</h1><p>ติดตามการขึ้นทะเบียนและงานบริการสัตว์ในพื้นที่เทศบาลท่าโพธ์</p></div><div className={`sync ${live?"ok":"demo"}`}><i/>{live?"เชื่อมต่อข้อมูลแล้ว":"ใช้ข้อมูลสำรอง"}</div></section><section className="stats-grid"><StatCard tone="green" icon="●" label="สัตว์ขึ้นทะเบียน" value={stats.total} detail={`${stats.dogs||0} สุนัข · ${stats.cats||0} แมว`}/><StatCard tone="amber" icon="⌁" label="คำขอรอตรวจสอบ" value={stats.pending} detail="ควรตรวจภายใน 3 วันทำการ"/><StatCard tone="blue" icon="+" label="รับวัคซีนปีนี้" value={stats.vaccinations} detail={`${vaccinationCoverage}% ของสัตว์ทั้งหมด`}/><StatCard tone="violet" icon="◇" label="ทำหมันแล้ว" value={stats.sterilizations} detail={`${sterilizationCoverage}% ของสัตว์ทั้งหมด`}/></section><section className="dashboard-focus-grid"><DashboardMap items={mapItems} villages={villages}/><aside className="panel coverage"><div className="panel-head"><div><h2>ความครอบคลุมบริการ</h2><p>เป้าหมายประจำปี 2569</p></div></div><Progress label="วัคซีนพิษสุนัขบ้า" value={vaccinationCoverage} color="green"/><Progress label="การทำหมัน" value={sterilizationCoverage} color="violet"/><div className="service-summary"><div><span>สัตว์ขึ้นทะเบียน</span><b>{total}</b></div><div><span>มีประวัติวัคซีน</span><b>{stats.vaccinations||0}</b></div><div><span>ทำหมันแล้ว</span><b>{stats.sterilizations||0}</b></div></div><div className="case-callout"><span>!</span><div><b>{stats.openCases||0} เหตุที่กำลังดำเนินการ</b><small>ตรวจสอบรายละเอียดในเมนูแจ้งเหตุ</small></div><button onClick={()=>navigate("cases")}>ตรวจสอบ</button></div></aside></section><section className="dashboard-bottom-grid"><article className="panel requests"><div className="panel-head"><div><h2>คำขอล่าสุด</h2><p>รายการที่ต้องดำเนินการ</p></div><button className="text-btn" onClick={()=>navigate("registrations")}>ดูทั้งหมด →</button></div><RequestTable requests={requests}/></article><article className="village-panel panel"><div className="panel-head"><div><h2>ภาพรวมรายหมู่บ้าน</h2><p>ความครอบคลุมวัคซีน</p></div><button className="text-btn" onClick={()=>navigate("reports")}>ดูรายงาน →</button></div><VillageBars rows={villages}/></article></section></>;
}
