import { useState } from "react";
import { ORGANIZATION } from "@prms/shared";
import { createApi } from "../lib/api.js";

export default function LoginPage({ onLogin }) {
  const [email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  const [challengeToken,setChallengeToken]=useState("");const[code,setCode]=useState("");
  async function submit(event){event.preventDefault();setBusy(true);setError("");try{const data=challengeToken?await createApi(null).post("/api/auth/mfa/verify",{challengeToken,code}):await createApi(null).post("/api/auth/login",{email,password});if(data.mfaRequired){setChallengeToken(data.challengeToken);return}sessionStorage.setItem("prms_access_token",data.token);onLogin(data.token)}catch(err){setError(err.message||"ไม่สามารถเข้าสู่ระบบได้")}finally{setBusy(false)}}
  return <main className="login-page"><section className="login-card"><div className="login-brand">ทพ</div><p className="eyebrow">{ORGANIZATION.productName}</p><h1>{challengeToken?"ยืนยันตัวตนสองขั้นตอน":"เข้าสู่ระบบเจ้าหน้าที่"}</h1><p>{challengeToken?"กรอกรหัส 6 หลักจากแอป Authenticator":ORGANIZATION.shortName}</p><form onSubmit={submit}>{challengeToken?<label>รหัสยืนยัน<input type="text" inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} pattern="\d{6}" required autoFocus/></label>:<><label>อีเมล<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>รหัสผ่าน<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} minLength="8" required placeholder="กรอกรหัสผ่าน"/></label></>}{error&&<div className="login-error">{error}</div>}<button disabled={busy}>{busy?"กำลังตรวจสอบ…":challengeToken?"ยืนยันรหัส":"เข้าสู่ระบบ"}</button>{challengeToken&&<button type="button" className="login-secondary" onClick={()=>{setChallengeToken('');setCode('');setError('')}}>กลับไปกรอกรหัสผ่าน</button>}</form><small>สำหรับเจ้าหน้าที่เทศบาลผู้ได้รับอนุญาตเท่านั้น</small></section></main>;
}
