import { useEffect, useMemo, useState } from "react";
import { createApi } from "../lib/api.js";

const regStatus = { SUBMITTED:"รอตรวจสอบ",UNDER_REVIEW:"กำลังตรวจ",NEED_MORE_INFO:"ขอข้อมูลเพิ่ม",APPROVED:"อนุมัติแล้ว",REJECTED:"ไม่อนุมัติ" };
const caseStatus = { RECEIVED:"รับเรื่องแล้ว",ASSIGNED:"มอบหมายแล้ว",IN_PROGRESS:"กำลังดำเนินการ",RESOLVED:"แก้ไขแล้ว",CLOSED:"ปิดเรื่อง" };
const speciesText = value => value === "DOG" ? "สุนัข" : "แมว";
const thaiDate = value => value ? new Date(value).toLocaleDateString("th-TH",{day:"numeric",month:"short",year:"2-digit"}) : "—";

function PageHead({ eyebrow, title, detail, actions }) { return <section className="page-title module-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{detail}</p></div>{actions}</section>; }
function Empty({ text="ยังไม่มีข้อมูลในส่วนนี้" }) { return <div className="module-empty"><i>◇</i><b>{text}</b><span>ข้อมูลใหม่จะแสดงที่นี่โดยอัตโนมัติ</span></div>; }
function Notice({ message, tone="error" }) { return message ? <div className={`module-notice ${tone}`}>{message}</div> : null; }

export function RegistrationsPage({ token, onChanged }) {
  const api=useMemo(()=>createApi(token),[token]); const [rows,setRows]=useState([]); const [filter,setFilter]=useState(""); const [busy,setBusy]=useState(""); const [message,setMessage]=useState("");
  const load=()=>api.get(`/api/admin/registrations${filter?`?status=${filter}`:""}`).then(setRows).catch(e=>setMessage(e.message));
  useEffect(load,[filter]);
  async function change(id,status){setBusy(id+status);setMessage("");try{await api.patch(`/api/admin/registrations/${id}/status`,{status});load();onChanged?.()}catch(e){setMessage(e.message)}finally{setBusy("")}}
  return <><PageHead eyebrow="งานทะเบียน" title="คำขอขึ้นทะเบียน" detail="ตรวจสอบข้อมูลจาก LINE และช่องทางออนไลน์ก่อนออกเลขทะเบียน" actions={<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">ทุกสถานะ</option>{Object.entries(regStatus).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select>} /><Notice message={message}/><article className="panel module-panel">{rows.length===0?<Empty text="ไม่มีคำขอในสถานะที่เลือก"/>:<div className="table-wrap"><table><thead><tr><th>เลขที่คำขอ</th><th>เจ้าของ / สัตว์</th><th>หมู่</th><th>ยื่นเมื่อ</th><th>สถานะ</th><th>ดำเนินการ</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.referenceNo}</b></td><td><div className="pet-cell"><i>{r.species==='DOG'?'ส':'ม'}</i><span><b>{r.petName}</b><small>{r.ownerName}</small></span></div></td><td>{r.villageNo}</td><td>{thaiDate(r.submittedAt)}</td><td><span className={`badge ${r.status==='APPROVED'?'green':r.status==='REJECTED'?'gray':'amber'}`}>{regStatus[r.status]}</span></td><td><div className="action-group">{!['APPROVED','REJECTED'].includes(r.status)&&<><button disabled={busy} onClick={()=>change(r.id,'UNDER_REVIEW')}>รับตรวจ</button><button className="approve" disabled={busy} onClick={()=>change(r.id,'APPROVED')}>อนุมัติ</button><button className="reject" disabled={busy} onClick={()=>change(r.id,'REJECTED')}>ไม่อนุมัติ</button></>}</div></td></tr>)}</tbody></table></div>}</article></>;
}

export function PetsPage({ token, serviceMode=false }) {
  const api=useMemo(()=>createApi(token),[token]); const [rows,setRows]=useState([]); const [search,setSearch]=useState(""); const [species,setSpecies]=useState(""); const [selected,setSelected]=useState(null); const [message,setMessage]=useState("");
  const load=()=>api.get(`/api/admin/pets?search=${encodeURIComponent(search)}${species?`&species=${species}`:""}`).then(setRows).catch(e=>setMessage(e.message));
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[search,species]);
  return <><PageHead eyebrow={serviceMode?"งานบริการสัตวแพทย์":"ทะเบียนกลาง"} title={serviceMode?"บันทึกวัคซีนและทำหมัน":"ข้อมูลสัตว์ขึ้นทะเบียน"} detail={serviceMode?"บันทึกบริการเป็นประวัติรายครั้ง ตรวจสอบย้อนหลังได้":"ค้นหาสัตว์ เจ้าของ เลขทะเบียน และสถานะสุขภาพ"} actions={<div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาชื่อ เจ้าของ โทรศัพท์…"/><select value={species} onChange={e=>setSpecies(e.target.value)}><option value="">ทุกชนิด</option><option value="DOG">สุนัข</option><option value="CAT">แมว</option></select></div>} /><Notice message={message}/><article className="panel module-panel">{rows.length===0?<Empty text="ยังไม่มีสัตว์ที่ผ่านการขึ้นทะเบียน"/>:<div className="table-wrap"><table><thead><tr><th>สัตว์</th><th>เลขทะเบียน</th><th>เจ้าของ</th><th>ที่อยู่</th><th>วัคซีนล่าสุด</th><th>ทำหมัน</th>{serviceMode&&<th>บันทึกบริการ</th>}</tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><div className="pet-cell"><i>{p.species==='DOG'?'ส':'ม'}</i><span><b>{p.petName}</b><small>{speciesText(p.species)} · {p.breed||'ไม่ระบุสายพันธุ์'}</small></span></div></td><td><b>{p.registrationNo||'รออนุมัติ'}</b></td><td>{p.ownerName}<small className="cell-sub">{p.phone}</small></td><td>{p.houseNo} หมู่ {p.villageNo}</td><td>{thaiDate(p.lastVaccinatedAt)}</td><td><span className={`badge ${p.sterilized?'green':'gray'}`}>{p.sterilized?'ทำแล้ว':'ยังไม่ทำ'}</span></td>{serviceMode&&<td><button className="service-btn" onClick={()=>setSelected(p)}>+ บันทึก</button></td>}</tr>)}</tbody></table></div>}</article>{selected&&<ServiceDialog pet={selected} api={api} onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);load()}}/>}</>;
}

function ServiceDialog({pet,api,onClose,onSaved}){const [type,setType]=useState("vaccine");const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [name,setName]=useState("วัคซีนป้องกันโรคพิษสุนัขบ้า");const [provider,setProvider]=useState("เทศบาลท่าโพธ์");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function save(e){e.preventDefault();setBusy(true);try{if(type==='vaccine')await api.post(`/api/admin/pets/${pet.id}/vaccinations`,{vaccineName:name,vaccinatedAt:date,providerName:provider,nextDueAt:"",lotNo:""});else await api.post(`/api/admin/pets/${pet.id}/sterilizations`,{sterilizedAt:date,providerName:provider,note:""});onSaved()}catch(err){setMessage(err.message)}finally{setBusy(false)}}return <div className="modal-backdrop"><form className="service-dialog" onSubmit={save}><div className="dialog-head"><div><p className="eyebrow">{pet.registrationNo}</p><h2>{pet.petName} · {pet.ownerName}</h2></div><button type="button" onClick={onClose}>×</button></div><label>ประเภทบริการ<select value={type} onChange={e=>setType(e.target.value)}><option value="vaccine">ฉีดวัคซีน</option><option value="sterilization">ทำหมัน</option></select></label>{type==='vaccine'&&<label>ชื่อวัคซีน<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>วันที่ให้บริการ<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>หน่วยบริการ<input value={provider} onChange={e=>setProvider(e.target.value)}/></label><Notice message={message}/><div className="dialog-actions"><button type="button" onClick={onClose}>ยกเลิก</button><button className="approve" disabled={busy}>{busy?'กำลังบันทึก…':'บันทึกประวัติ'}</button></div></form></div>}

export function CasesPage({token}){const api=useMemo(()=>createApi(token),[token]);const[rows,setRows]=useState([]);const[message,setMessage]=useState("");const load=()=>api.get('/api/admin/cases').then(setRows).catch(e=>setMessage(e.message));useEffect(load,[]);async function change(id,status){try{await api.patch(`/api/admin/cases/${id}/status`,{status});load()}catch(e){setMessage(e.message)}}return <><PageHead eyebrow="ศูนย์รับแจ้ง" title="แจ้งเหตุและร้องเรียน" detail="ติดตามเหตุสัตว์จรจัด กัดทำร้าย เจ็บป่วย และเหตุรำคาญ"/><Notice message={message}/><article className="panel module-panel">{rows.length===0?<Empty text="ขณะนี้ไม่มีเหตุที่รับแจ้ง"/>:<div className="case-list">{rows.map(c=><div className="case-row" key={c.id}><div className="case-symbol">!</div><div><b>{c.referenceNo} · {c.category}</b><p>{c.description}</p><small>หมู่ {c.villageNo} · {thaiDate(c.createdAt)} · {c.reporterName||'ไม่ระบุผู้แจ้ง'}</small></div><select value={c.status} onChange={e=>change(c.id,e.target.value)}>{Object.entries(caseStatus).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></div>)}</div>}</article></>}

export function ReportsPage({token,mapOnly=false}){
  const api=useMemo(()=>createApi(token),[token]);
  const[rows,setRows]=useState([]);const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
  const load=()=>{setLoading(true);setMessage("");api.get('/api/admin/reports/villages').then(data=>setRows(Array.isArray(data)?data:[])).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))};
  useEffect(load,[api]);
  const totals=rows.reduce((a,r)=>({pets:a.pets+Number(r.totalPets||0),dogs:a.dogs+Number(r.dogs||0),cats:a.cats+Number(r.cats||0),vaccinated:a.vaccinated+Number(r.vaccinated||0),sterilized:a.sterilized+Number(r.sterilized||0)}),{pets:0,dogs:0,cats:0,vaccinated:0,sterilized:0});
  const vaccineCoverage=totals.pets?Math.round(totals.vaccinated*100/totals.pets):0;
  const sterilizationCoverage=totals.pets?Math.round(totals.sterilized*100/totals.pets):0;
  return <><PageHead eyebrow={mapOnly?'ข้อมูลเชิงพื้นที่':'รายงานผู้บริหาร'} title={mapOnly?'ภาพรวมพื้นที่ 11 หมู่บ้าน':'รายงานทะเบียนสัตว์'} detail={mapOnly?'แสดงข้อมูลรายหมู่บ้านระหว่างรอรับแนวเขต GIS ทางราชการ':'สรุปสัตว์ขึ้นทะเบียน วัคซีน และการทำหมัน แยกรายหมู่บ้าน'} actions={!mapOnly&&<div className="report-actions"><button className="refresh-btn" onClick={load} disabled={loading}>↻ อัปเดตข้อมูล</button><button className="export-btn" onClick={()=>exportCsv(rows)} disabled={!rows.length}>ส่งออก CSV</button></div>}/><Notice message={message}/>
    {loading?<article className="panel report-loading"><i/><b>กำลังจัดทำรายงาน…</b><span>กำลังรวบรวมข้อมูลจากทะเบียนกลาง</span></article>:rows.length===0?<article className="panel report-empty"><b>ยังไม่มีข้อมูลสำหรับจัดทำรายงาน</b><span>ลองอัปเดตข้อมูลอีกครั้ง หรือตรวจสอบรายการทะเบียนที่อนุมัติแล้ว</span><button onClick={load}>ลองใหม่</button></article>:<>
      {!mapOnly&&<section className="report-stats report-stats-six"><article><span>สัตว์ขึ้นทะเบียน</span><b>{totals.pets.toLocaleString('th-TH')}</b><small>ตัว</small></article><article><span>สุนัข</span><b>{totals.dogs.toLocaleString('th-TH')}</b><small>ตัว</small></article><article><span>แมว</span><b>{totals.cats.toLocaleString('th-TH')}</b><small>ตัว</small></article><article className="green"><span>รับวัคซีน</span><b>{vaccineCoverage}%</b><small>{totals.vaccinated} ตัว</small></article><article className="violet"><span>ทำหมันแล้ว</span><b>{sterilizationCoverage}%</b><small>{totals.sterilized} ตัว</small></article><article><span>พื้นที่ครอบคลุม</span><b>{rows.length}</b><small>หมู่บ้าน</small></article></section>}
      <article className="panel module-panel report-panel"><div className="panel-head"><div><h2>สรุปรายหมู่บ้าน</h2><p>เปรียบเทียบความครอบคลุมบริการของเทศบาลท่าโพธ์</p></div><span className="report-period">ข้อมูลปัจจุบัน</span></div><div className="report-table-wrap"><table className="report-table"><thead><tr><th>หมู่บ้าน</th><th>สัตว์ทั้งหมด</th><th>สุนัข</th><th>แมว</th><th>วัคซีน</th><th>ทำหมัน</th><th>ความครอบคลุมวัคซีน</th></tr></thead><tbody>{rows.map(r=>{const total=Number(r.totalPets||0);const vaccinated=Number(r.vaccinated||0);const coverage=total?Math.round(vaccinated*100/total):0;return <tr key={r.villageNo}><td><div className="report-village"><i>{r.villageNo}</i><b>{r.villageName}</b></div></td><td><strong>{total.toLocaleString('th-TH')}</strong> ตัว</td><td>{Number(r.dogs||0).toLocaleString('th-TH')}</td><td>{Number(r.cats||0).toLocaleString('th-TH')}</td><td>{vaccinated.toLocaleString('th-TH')}</td><td>{Number(r.sterilized||0).toLocaleString('th-TH')}</td><td><div className="coverage-cell"><em><strong style={{width:`${coverage}%`}}/></em><b>{coverage}%</b></div></td></tr>})}</tbody></table></div></article>
    </>}{mapOnly&&<div className="gis-note">แนวเขตและพิกัดบ้านจะเปิดใช้เมื่อเทศบาลยืนยันชุดข้อมูล GIS อย่างเป็นทางการ เพื่อไม่แสดงตำแหน่งคลาดเคลื่อน</div>}</>;
}
function safeCsv(value){let text=String(value??'');if(/^[=+\-@]/.test(text))text=`'${text}`;return `"${text.replaceAll('"','""')}"`}
function exportCsv(rows){const data=[["หมู่","สัตว์ทั้งหมด","สุนัข","แมว","ฉีดวัคซีน","ทำหมัน"],...rows.map(r=>[r.villageNo,r.totalPets,r.dogs,r.cats,r.vaccinated,r.sterilized])];const blob=new Blob(['\uFEFF'+data.map(row=>row.map(safeCsv).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='PRMS-TSM_รายงานรายหมู่บ้าน.csv';a.click();URL.revokeObjectURL(url)}

export function SettingsPage(){return <><PageHead eyebrow="การตั้งค่าระบบ" title="ช่องทางและความปลอดภัย" detail="สถานะองค์ประกอบสำคัญของ PRMS-TSM"/><section className="settings-grid"><article className="panel"><i className="setting-icon">A</i><div><b>Admin Web</b><span>ระบบหลักสำหรับเจ้าหน้าที่</span></div><em className="ready">พร้อมใช้งาน</em></article><article className="panel"><i className="setting-icon line">L</i><div><b>LINE LIFF</b><span>ช่องทางหลักสำหรับเจ้าของสัตว์</span></div><em className="waiting">รอ Channel ID</em></article><article className="panel"><i className="setting-icon">DB</i><div><b>ฐานข้อมูลกลาง</b><span>MariaDB · Audit log เปิดใช้งาน</span></div><em className="ready">เชื่อมต่อแล้ว</em></article><article className="panel"><i className="setting-icon">W</i><div><b>Citizen Web</b><span>ช่องทางสำรองเมื่อใช้ LINE ไม่ได้</span></div><em className="ready">พร้อมใช้งาน</em></article></section></>}
