export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "PRMS-TSM API",
    version: "1.0.0",
    description: "API ระบบขึ้นทะเบียนและบริหารจัดการข้อมูลสุนัขและแมว เทศบาลท่าโพธ์",
  },
  servers: [
    { url: "/api/v1", description: "API contract เวอร์ชัน 1" },
    { url: "/api", description: "เส้นทางเดิมเพื่อความเข้ากันได้" },
  ],
  tags: [
    { name: "Public" }, { name: "Citizen" }, { name: "Authentication" },
    { name: "Admin" }, { name: "Reports" }, { name: "Monitoring" },
  ],
  components: {
    securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } },
    schemas: {
      Error: { type: "object", required: ["message"], properties: { message: { type: "string" }, errors: { type: "object", additionalProperties: { type: "string" } } } },
      RegistrationInput: { type: "object", required: ["ownerName", "phone", "houseNo", "villageId", "petName", "species"], properties: { ownerName: { type: "string" }, phone: { type: "string", pattern: "^0[0-9]{9}$" }, nationalId: { type: "string" }, houseNo: { type: "string" }, villageId: { type: "integer" }, addressDetail: { type: "string" }, petName: { type: "string" }, species: { enum: ["DOG", "CAT"] }, sex: { enum: ["MALE", "FEMALE", "UNKNOWN"] }, breed: { type: "string" }, color: { type: "string" }, birthDate: { type: "string", format: "date" } } },
    },
  },
  paths: {
    "/openapi.json": { get: { tags: ["Monitoring"], summary: "OpenAPI document", responses: { 200: { description: "OpenAPI 3.1 document" } } } },
    "/health": { get: { tags: ["Monitoring"], summary: "สถานะ API และฐานข้อมูล", responses: { 200: { description: "Health status" } } } },
    "/health/live": { get: { tags: ["Monitoring"], summary: "Liveness probe", responses: { 200: { description: "Process is alive" } } } },
    "/health/ready": { get: { tags: ["Monitoring"], summary: "Readiness probe", responses: { 200: { description: "Ready" }, 503: { description: "Not ready" } } } },
    "/public/villages": { get: { tags: ["Public"], summary: "รายชื่อหมู่บ้าน", responses: { 200: { description: "Village list" } } } },
    "/public/registrations": { post: { tags: ["Public"], summary: "ส่งข้อมูลขึ้นทะเบียนสัตว์เลี้ยง", parameters: [{ in: "header", name: "Idempotency-Key", schema: { type: "string", maxLength: 128 } }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/RegistrationInput" } } } }, responses: { 201: { description: "Created" }, 200: { description: "Idempotent replay" }, 422: { description: "Invalid input" } } } },
    "/public/registrations/{referenceNo}": { get: { tags: ["Public"], summary: "ติดตามข้อมูลขึ้นทะเบียน", parameters: [{ in: "path", name: "referenceNo", required: true, schema: { type: "string" } }], responses: { 200: { description: "Registration status" }, 404: { description: "Not found" } } } },
    "/public/line-config": { get: { tags: ["Public"], summary: "สถานะและ LIFF ID สาธารณะ", responses: { 200: { description: "LINE configuration" } } } },
    "/citizen/line/session": { post: { tags: ["Citizen"], summary: "ยืนยัน LINE ID Token", responses: { 200: { description: "Citizen session" }, 401: { description: "Invalid LINE token" } } } },
    "/citizen/line/link": { post: { tags: ["Citizen"], summary: "ผูก LINE กับทะเบียนเจ้าของ", security: [{ bearerAuth: [] }], responses: { 200: { description: "Linked" } } } },
    "/citizen/me": { get: { tags: ["Citizen"], summary: "สัตว์เลี้ยงและข้อมูลที่เจ้าของส่ง", security: [{ bearerAuth: [] }], responses: { 200: { description: "Citizen data" } } } },
    "/citizen/pets/{id}/submissions": { post: { tags: ["Citizen"], summary: "ส่งข้อมูลแก้ทะเบียน วัคซีน ทำหมัน หรือสถานะสัตว์เลี้ยง", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "id", required: true, schema: { type: "string", format: "uuid" } }], responses: { 201: { description: "Submitted for staff review" }, 409: { description: "A pending submission already exists" } } } },
    "/citizen/submissions/{id}": { get: { tags: ["Citizen"], summary: "ดูรายละเอียดข้อมูลที่ส่งเพื่อแก้ไข", security: [{ bearerAuth: [] }], responses: { 200: { description: "Owned submission detail" }, 404: { description: "Not found or not owned" } } } },
    "/citizen/submissions/{id}/resubmit": { patch: { tags: ["Citizen"], summary: "แก้ไขข้อมูลที่เจ้าหน้าที่ส่งกลับ", security: [{ bearerAuth: [] }], responses: { 200: { description: "Resubmitted" }, 409: { description: "State or version conflict" } } } },
    "/citizen/submissions/{id}/cancel": { patch: { tags: ["Citizen"], summary: "ยกเลิกข้อมูลที่ยังไม่รับรอง", security: [{ bearerAuth: [] }], responses: { 200: { description: "Cancelled" }, 409: { description: "Version conflict" } } } },
    "/auth/login": { post: { tags: ["Authentication"], summary: "เข้าสู่ระบบเจ้าหน้าที่", responses: { 200: { description: "JWT session" }, 401: { description: "Invalid credentials" }, 423: { description: "Account locked" } } } },
    "/auth/mfa/verify": { post: { tags: ["Authentication"], summary: "ยืนยันรหัส MFA เพื่อรับ JWT session", responses: { 200: { description: "JWT session" }, 401: { description: "Invalid code" } } } },
    "/auth/mfa/status": { get: { tags: ["Authentication"], summary: "สถานะ MFA ของบัญชีปัจจุบัน", security: [{ bearerAuth: [] }], responses: { 200: { description: "MFA status" } } } },
    "/auth/mfa/setup": { post: { tags: ["Authentication"], summary: "เริ่มตั้งค่า Authenticator", security: [{ bearerAuth: [] }], responses: { 200: { description: "Encrypted MFA setup" } } } },
    "/auth/mfa/enable": { post: { tags: ["Authentication"], summary: "ยืนยันและเปิด MFA", security: [{ bearerAuth: [] }], responses: { 200: { description: "MFA enabled" } } } },
    "/admin/dashboard": { get: { tags: ["Admin"], summary: "ข้อมูลภาพรวม", security: [{ bearerAuth: [] }], responses: { 200: { description: "Dashboard" } } } },
    "/admin/owners": { get: { tags: ["Admin"], summary: "ทะเบียนเจ้าของ", security: [{ bearerAuth: [] }], responses: { 200: { description: "Owners" } } } },
    "/admin/owners/{id}": { get: { tags: ["Admin"], summary: "รายละเอียดเจ้าของ", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "id", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Owner" } } }, patch: { tags: ["Admin"], summary: "แก้ไขเจ้าของและที่อยู่", security: [{ bearerAuth: [] }], responses: { 200: { description: "Updated" } } } },
    "/admin/users": { get: { tags: ["Admin"], summary: "บัญชีเจ้าหน้าที่", security: [{ bearerAuth: [] }], responses: { 200: { description: "Users" } } } },
    "/admin/users/{id}": { patch: { tags: ["Admin"], summary: "แก้บทบาท สถานะ และพื้นที่รับผิดชอบ", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "id", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Updated" } } } },
    "/admin/system-status": { get: { tags: ["Admin"], summary: "สถานะองค์ประกอบระบบ", security: [{ bearerAuth: [] }], responses: { 200: { description: "System status" } } } },
    "/admin/registrations": { get: { tags: ["Admin"], summary: "ข้อมูลขึ้นทะเบียนที่รอตรวจสอบ", security: [{ bearerAuth: [] }], responses: { 200: { description: "Registrations" } } } },
    "/admin/registrations/{id}": { get: { tags: ["Admin"], summary: "รายละเอียดข้อมูลและหลักฐาน", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "id", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Registration detail" } } } },
    "/admin/attachments/{id}": { get: { tags: ["Admin"], summary: "ดาวน์โหลดไฟล์หลักฐานส่วนตัว", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "id", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Private attachment" }, 404: { description: "Not found or out of scope" } } } },
    "/admin/citizen-submissions": { get: { tags: ["Admin"], summary: "คิวข้อมูลเปลี่ยนแปลงจาก LINE", security: [{ bearerAuth: [] }], responses: { 200: { description: "Paginated submission queue" } } } },
    "/admin/citizen-submissions/{id}": { get: { tags: ["Admin"], summary: "เปรียบเทียบข้อมูลปัจจุบันและข้อมูลที่เสนอ", security: [{ bearerAuth: [] }], responses: { 200: { description: "Submission detail" } } } },
    "/admin/citizen-submissions/{id}/status": { patch: { tags: ["Admin"], summary: "ตรวจและรับรองข้อมูลด้วย optimistic version", security: [{ bearerAuth: [] }], responses: { 200: { description: "Reviewed" }, 409: { description: "State or version conflict" } } } },
    "/admin/registrations/{id}/status": { patch: { tags: ["Admin"], summary: "บันทึกผลตรวจข้อมูลขึ้นทะเบียน", security: [{ bearerAuth: [] }], responses: { 200: { description: "Status updated and LINE notification attempted" } } } },
    "/admin/pets": { get: { tags: ["Admin"], summary: "ทะเบียนสัตว์", security: [{ bearerAuth: [] }], responses: { 200: { description: "Pets" } } } },
    "/admin/pets/{id}": { get: { tags: ["Admin"], summary: "รายละเอียดและประวัติสัตว์", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "id", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Pet detail" } } } },
    "/admin/pets/{id}/status": { patch: { tags: ["Admin"], summary: "เปลี่ยนสถานะสัตว์", security: [{ bearerAuth: [] }], responses: { 200: { description: "Status updated" } } } },
    "/admin/pets/{id}/owner": { patch: { tags: ["Admin"], summary: "โอนเจ้าของสัตว์", security: [{ bearerAuth: [] }], responses: { 200: { description: "Owner transferred" } } } },
    "/admin/pets/{petId}/vaccinations": { post: { tags: ["Admin"], summary: "บันทึกวัคซีน", security: [{ bearerAuth: [] }], responses: { 201: { description: "Vaccination recorded" } } } },
    "/admin/vaccinations/{id}": { patch: { tags: ["Admin"], summary: "แก้ไขประวัติวัคซีน", security: [{ bearerAuth: [] }], responses: { 200: { description: "Vaccination updated" } } } },
    "/admin/pets/{petId}/sterilizations": { post: { tags: ["Admin"], summary: "บันทึกการทำหมัน", security: [{ bearerAuth: [] }], responses: { 201: { description: "Sterilization recorded" } } } },
    "/admin/sterilizations/{id}": { patch: { tags: ["Admin"], summary: "แก้ไขประวัติทำหมัน", security: [{ bearerAuth: [] }], responses: { 200: { description: "Sterilization updated" } } } },
    "/admin/map": { get: { tags: ["Admin"], summary: "ข้อมูลตำแหน่งแผนที่", security: [{ bearerAuth: [] }], responses: { 200: { description: "Map points" } } } },
    "/admin/cases": { get: { tags: ["Admin"], summary: "รายการแจ้งเหตุ", security: [{ bearerAuth: [] }], responses: { 200: { description: "Cases" } } } },
    "/admin/cases/{id}/status": { patch: { tags: ["Admin"], summary: "เปลี่ยนสถานะแจ้งเหตุ", security: [{ bearerAuth: [] }], responses: { 200: { description: "Case updated" } } } },
    "/admin/audit-logs": { get: { tags: ["Admin"], summary: "Audit Log", security: [{ bearerAuth: [] }], responses: { 200: { description: "Audit events" } } } },
    "/admin/reports/villages-v2": { get: { tags: ["Reports"], summary: "รายงานรายหมู่บ้านตามวันตัดยอด", security: [{ bearerAuth: [] }], responses: { 200: { description: "Report data" } } } },
    "/admin/reports/villages/export/{format}": { get: { tags: ["Reports"], summary: "ส่งออกรายงาน PDF/XLSX", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "format", required: true, schema: { enum: ["pdf", "xlsx"] } }, { in: "query", name: "cutoff", schema: { type: "string", format: "date" } }, { in: "query", name: "villageId", schema: { type: "integer" } }], responses: { 200: { description: "Report file" } } } },
    "/admin/reports/{type}/export/{format}": { get: { tags: ["Reports"], summary: "ส่งออกรายงานทะเบียน วัคซีน ทำหมัน SLA หรือคุณภาพข้อมูล", security: [{ bearerAuth: [] }], parameters: [{ in: "path", name: "type", required: true, schema: { enum: ["registry", "vaccination", "sterilization", "submissions", "data-quality"] } }, { in: "path", name: "format", required: true, schema: { enum: ["pdf", "xlsx"] } }], responses: { 200: { description: "Report file" }, 422: { description: "Unsupported format" } } } },
    "/admin/reports/villages": { get: { deprecated: true, tags: ["Reports"], summary: "รายงานรายหมู่บ้านแบบเดิม", security: [{ bearerAuth: [] }], responses: { 200: { description: "Legacy report data" } } } },
  },
};
