import { useEffect, useState } from "react";
import { ORGANIZATION, normalizeThaiPhone, validatePetRegistration } from "@prms/shared";

const empty = { ownerName:"", phone:"", nationalId:"", houseNo:"", villageId:"", addressDetail:"", petName:"", species:"DOG", sex:"UNKNOWN", breed:"", color:"", birthDate:"" };
const fallbackVillages = Array.from({length:11},(_,i)=>({id:i+1,villageNo:i+1,name:`หมู่ที่ ${i+1}`}));

export default function App(){
  const [view,setView]=useState("home"); const [form,setForm]=useState(empty); const [errors,setErrors]=useState({});
  const [villages,setVillages]=useState(fallbackVillages); const [saving,setSaving]=useState(false); const [result,setResult]=useState(null);
  const [reference,setReference]=useState(""); const [tracking,setTracking]=useState(null); const [message,setMessage]=useState("");
  useEffect(()=>{fetch('/api/public/villages').then(r=>r.ok?r.json():Promise.reject()).then(r=>setVillages(r.data)).catch(()=>{})},[]);
  const update=e=>setForm(v=>({...v,[e.target.name]:e.target.name==='phone'?normalizeThaiPhone(e.target.value):e.target.value}));
  async function submit(e){e.preventDefault();const check=validatePetRegistration(form);setErrors(check.errors);if(!check.valid)return;setSaving(true);setMessage("");try{const r=await fetch('/api/public/registrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const body=await r.json();if(!r.ok)throw new Error(body.message);setResult(body.data);setView('success')}catch(err){setMessage(err.message||'ไม่สามารถส่งข้อมูลได้')}finally{setSaving(false)}}
  async function track(e){e.preventDefault();setMessage("");try{const r=await fetch(`/api/public/registrations/${encodeURIComponent(reference.trim())}`);const body=await r.json();if(!r.ok)throw new Error(body.message);setTracking(body.data)}catch(err){setTracking(null);setMessage(err.message)}}
  return <div className="site"><header><div className="seal">ทพ</div><div><b>{ORGANIZATION.shortName}</b><span>{ORGANIZATION.productName} · {ORGANIZATION.systemName}</span></div><button onClick={()=>setView('track')}>ติดตามคำขอ</button></header>
    {view==='home'&&<main className="home"><section className="hero"><p className="tag">บริการออนไลน์สำหรับประชาชน</p><h1>ลงทะเบียนสัตว์เลี้ยง<br/><em>ง่าย ครบ จบในที่เดียว</em></h1><p>แจ้งข้อมูลสุนัขและแมว ตรวจสอบสถานะ และเข้าถึงบริการของเทศบาลท่าโพธ์ได้สะดวกยิ่งขึ้น</p><div className="hero-actions"><button className="primary" onClick={()=>setView('form')}>เริ่มขึ้นทะเบียนสัตว์ <span>→</span></button><button className="secondary" onClick={()=>setView('track')}>ตรวจสอบสถานะ</button></div><div className="trust"><span>✓ ข้อมูลถูกจัดเก็บอย่างปลอดภัย</span><span>✓ ใช้เวลาเพียง 5–10 นาที</span></div></section><section className="pet-card"><div className="sun"/><div className="dog">ส</div><div className="cat">ม</div><div className="grass"/><aside><b>สัตว์เลี้ยงมีทะเบียน</b><span>ช่วยให้เทศบาลวางแผนวัคซีนและควบคุมโรคได้แม่นยำ</span></aside></section></main>}
    {view==='form'&&<main className="form-page"><button className="back" onClick={()=>setView('home')}>← กลับหน้าหลัก</button><div className="form-head"><p className="tag">แบบคำขอออนไลน์</p><h1>ขึ้นทะเบียนสุนัขและแมว</h1><p>กรอกข้อมูลตามจริง เจ้าหน้าที่จะตรวจสอบภายใน 3 วันทำการ</p></div><form onSubmit={submit}><FormSection no="01" title="ข้อมูลเจ้าของสัตว์"><Field label="ชื่อ–นามสกุล" name="ownerName" value={form.ownerName} onChange={update} error={errors.ownerName}/><Field label="หมายเลขโทรศัพท์" name="phone" inputMode="numeric" value={form.phone} onChange={update} error={errors.phone}/><Field label="เลขประจำตัวประชาชน (ถ้ามี)" name="nationalId" inputMode="numeric" maxLength="13" value={form.nationalId} onChange={update}/></FormSection><FormSection no="02" title="ที่อยู่ในเขตเทศบาล"><Field label="เลขที่บ้าน" name="houseNo" value={form.houseNo} onChange={update} error={errors.houseNo}/><label>หมู่บ้าน<select name="villageId" value={form.villageId} onChange={update}><option value="">เลือกหมู่บ้าน</option>{villages.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select>{errors.villageId&&<small>{errors.villageId}</small>}</label><Field label="รายละเอียดที่อยู่เพิ่มเติม" name="addressDetail" value={form.addressDetail} onChange={update}/></FormSection><FormSection no="03" title="ข้อมูลสัตว์เลี้ยง"><Field label="ชื่อสัตว์" name="petName" value={form.petName} onChange={update} error={errors.petName}/><label>ชนิดสัตว์<select name="species" value={form.species} onChange={update}><option value="DOG">สุนัข</option><option value="CAT">แมว</option></select></label><label>เพศ<select name="sex" value={form.sex} onChange={update}><option value="UNKNOWN">ไม่ระบุ</option><option value="MALE">เพศผู้</option><option value="FEMALE">เพศเมีย</option></select></label><Field label="สายพันธุ์" name="breed" value={form.breed} onChange={update}/><Field label="สี/ตำหนิ" name="color" value={form.color} onChange={update}/><Field label="วันเกิดโดยประมาณ" name="birthDate" type="date" value={form.birthDate} onChange={update}/></FormSection>{message&&<div className="error-box">{message}</div>}<div className="consent"><input type="checkbox" required id="consent"/><label htmlFor="consent">ข้าพเจ้ารับรองว่าข้อมูลถูกต้อง และยินยอมให้เทศบาลท่าโพธ์ใช้ข้อมูลเพื่อการขึ้นทะเบียนและบริการสาธารณสุขสัตว์</label></div><button className="submit" disabled={saving}>{saving?'กำลังส่งข้อมูล…':'ยืนยันและส่งคำขอ →'}</button></form></main>}
    {view==='track'&&<main className="narrow"><button className="back" onClick={()=>setView('home')}>← กลับหน้าหลัก</button><div className="track-card"><div className="round-icon">⌕</div><p className="tag">ติดตามคำขอ</p><h1>ตรวจสอบสถานะการขึ้นทะเบียน</h1><p>กรอกเลขที่คำขอที่ได้รับหลังส่งข้อมูล</p><form onSubmit={track}><input value={reference} onChange={e=>setReference(e.target.value.toUpperCase())} placeholder="เช่น TSM-2569-100241" required/><button>ตรวจสอบ</button></form>{message&&<div className="error-box">{message}</div>}{tracking&&<div className="tracking"><span>เลขที่ {tracking.referenceNo}</span><b>{tracking.status==='APPROVED'?'อนุมัติแล้ว':'อยู่ระหว่างดำเนินการ'}</b><small>สถานะระบบ: {tracking.status}</small></div>}</div></main>}
    {view==='success'&&<main className="narrow"><div className="track-card success"><div className="check">✓</div><p className="tag">ส่งคำขอสำเร็จ</p><h1>เทศบาลได้รับข้อมูลแล้ว</h1><p>โปรดบันทึกเลขที่คำขอสำหรับติดตามผล</p><strong className="reference">{result?.referenceNo}</strong><button className="primary" onClick={()=>{setReference(result?.referenceNo||'');setView('track')}}>ติดตามคำขอนี้</button><button className="link" onClick={()=>{setForm(empty);setView('home')}}>กลับหน้าหลัก</button></div></main>}
    <footer><b>{ORGANIZATION.shortName}</b><span>ระบบ PRMS-TSM · บริการประชาชนด้านสุขภาพสัตว์</span></footer></div>
}

function Field({label,error,...props}){return <label>{label}<input {...props}/>{error&&<small>{error}</small>}</label>}
function FormSection({no,title,children}){return <section className="form-section"><div className="section-title"><i>{no}</i><h2>{title}</h2></div><div className="fields">{children}</div></section>}
