import { useEffect, useMemo, useState } from "react";
import { ORGANIZATION, normalizeThaiPhone, validatePetRegistration } from "@prms/shared";
import { createCitizenApi } from "./api.js";
import { connectLine } from "./line.js";

const empty = { ownerName:"", phone:"", nationalId:"", houseNo:"", villageId:"", addressDetail:"", petName:"", species:"DOG", sex:"UNKNOWN", breed:"", color:"", birthDate:"" };
const fallbackVillages = Array.from({length:11},(_,i)=>({id:i+1,villageNo:i+1,name:`หมู่ที่ ${i+1}`}));

export default function App(){
  const [citizenToken,setCitizenToken]=useState(()=>sessionStorage.getItem("prms_citizen_token")||"");
  const publicApi=useMemo(()=>createCitizenApi(),[]); const citizenApi=useMemo(()=>createCitizenApi(citizenToken),[citizenToken]);
  const [view,setView]=useState("home"); const [form,setForm]=useState(empty); const [errors,setErrors]=useState({});
  const [villages,setVillages]=useState(fallbackVillages); const [saving,setSaving]=useState(false); const [result,setResult]=useState(null);
  const [reference,setReference]=useState(""); const [tracking,setTracking]=useState(null); const [message,setMessage]=useState("");
  const [lineSession,setLineSession]=useState(null); const [myData,setMyData]=useState(null); const [lineBusy,setLineBusy]=useState(false); const [linkForm,setLinkForm]=useState({referenceNo:"",phone:""});
  useEffect(()=>{publicApi.get('/public/villages').then(setVillages).catch(()=>{})},[publicApi]);
  const update=e=>setForm(v=>({...v,[e.target.name]:e.target.name==='phone'?normalizeThaiPhone(e.target.value):e.target.value}));
  async function submit(e){e.preventDefault();const check=validatePetRegistration(form);setErrors(check.errors);if(!check.valid)return;setSaving(true);setMessage("");try{const data=await publicApi.post('/public/registrations',form);setResult(data);setView('success')}catch(err){setMessage(err.message||'ไม่สามารถส่งข้อมูลได้')}finally{setSaving(false)}}
  async function track(e){e.preventDefault();setMessage("");try{setTracking(await publicApi.get(`/public/registrations/${encodeURIComponent(reference.trim())}`))}catch(err){setTracking(null);setMessage(err.message)}}
  async function loadMyData(token=citizenToken){if(!token)return;const data=await createCitizenApi(token).get('/citizen/me');setMyData(data)}
  async function openLine(){setView('line');setMessage("");setLineBusy(true);try{if(citizenToken){await loadMyData();return}const session=await connectLine(publicApi);if(!session)return;sessionStorage.setItem('prms_citizen_token',session.token);setCitizenToken(session.token);setLineSession(session);await loadMyData(session.token)}catch(err){setMessage(err.message)}finally{setLineBusy(false)}}
  async function linkOwner(e){e.preventDefault();setLineBusy(true);setMessage("");try{const data=await citizenApi.post('/citizen/line/link',{referenceNo:linkForm.referenceNo.trim().toUpperCase(),phone:normalizeThaiPhone(linkForm.phone)});sessionStorage.setItem('prms_citizen_token',data.token);setCitizenToken(data.token);await loadMyData(data.token)}catch(err){setMessage(err.message)}finally{setLineBusy(false)}}
  return <div className="site"><header><div className="seal">ทพ</div><div><b>{ORGANIZATION.shortName}</b><span>{ORGANIZATION.productName} · {ORGANIZATION.systemName}</span></div><div className="header-actions"><button onClick={()=>setView('track')}>ติดตามคำขอ</button><button className="line-button" onClick={openLine}>LINE / สัตว์ของฉัน</button></div></header>
    {view==='home'&&<main className="home"><section className="hero"><p className="tag">บริการออนไลน์สำหรับประชาชน</p><h1>ลงทะเบียนสัตว์เลี้ยง<br/><em>ง่าย ครบ จบในที่เดียว</em></h1><p>แจ้งข้อมูลสุนัขและแมว ตรวจสอบสถานะ และเข้าถึงบริการของเทศบาลท่าโพธ์ได้สะดวกยิ่งขึ้น</p><div className="hero-actions"><button className="primary" onClick={()=>setView('form')}>เริ่มขึ้นทะเบียนสัตว์ <span>→</span></button><button className="secondary" onClick={()=>setView('track')}>ตรวจสอบสถานะ</button></div><div className="trust"><span>✓ ข้อมูลถูกจัดเก็บอย่างปลอดภัย</span><span>✓ ใช้เวลาเพียง 5–10 นาที</span></div></section><section className="pet-card"><div className="sun"/><div className="dog">ส</div><div className="cat">ม</div><div className="grass"/><aside><b>สัตว์เลี้ยงมีทะเบียน</b><span>ช่วยให้เทศบาลวางแผนวัคซีนและควบคุมโรคได้แม่นยำ</span></aside></section></main>}
    {view==='form'&&<main className="form-page"><button className="back" onClick={()=>setView('home')}>← กลับหน้าหลัก</button><div className="form-head"><p className="tag">แบบคำขอออนไลน์</p><h1>ขึ้นทะเบียนสุนัขและแมว</h1><p>กรอกข้อมูลตามจริง เจ้าหน้าที่จะตรวจสอบภายใน 3 วันทำการ</p></div><form onSubmit={submit}><FormSection no="01" title="ข้อมูลเจ้าของสัตว์"><Field label="ชื่อ–นามสกุล" name="ownerName" value={form.ownerName} onChange={update} error={errors.ownerName}/><Field label="หมายเลขโทรศัพท์" name="phone" inputMode="numeric" value={form.phone} onChange={update} error={errors.phone}/><Field label="เลขประจำตัวประชาชน (ถ้ามี)" name="nationalId" inputMode="numeric" maxLength="13" value={form.nationalId} onChange={update}/></FormSection><FormSection no="02" title="ที่อยู่ในเขตเทศบาล"><Field label="เลขที่บ้าน" name="houseNo" value={form.houseNo} onChange={update} error={errors.houseNo}/><label>หมู่บ้าน<select name="villageId" value={form.villageId} onChange={update}><option value="">เลือกหมู่บ้าน</option>{villages.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select>{errors.villageId&&<small>{errors.villageId}</small>}</label><Field label="รายละเอียดที่อยู่เพิ่มเติม" name="addressDetail" value={form.addressDetail} onChange={update}/></FormSection><FormSection no="03" title="ข้อมูลสัตว์เลี้ยง"><Field label="ชื่อสัตว์" name="petName" value={form.petName} onChange={update} error={errors.petName}/><label>ชนิดสัตว์<select name="species" value={form.species} onChange={update}><option value="DOG">สุนัข</option><option value="CAT">แมว</option></select></label><label>เพศ<select name="sex" value={form.sex} onChange={update}><option value="UNKNOWN">ไม่ระบุ</option><option value="MALE">เพศผู้</option><option value="FEMALE">เพศเมีย</option></select></label><Field label="สายพันธุ์" name="breed" value={form.breed} onChange={update}/><Field label="สี/ตำหนิ" name="color" value={form.color} onChange={update}/><Field label="วันเกิดโดยประมาณ" name="birthDate" type="date" value={form.birthDate} onChange={update}/></FormSection>{message&&<div className="error-box">{message}</div>}<div className="consent"><input type="checkbox" required id="consent"/><label htmlFor="consent">ข้าพเจ้ารับรองว่าข้อมูลถูกต้อง และยินยอมให้เทศบาลท่าโพธ์ใช้ข้อมูลเพื่อการขึ้นทะเบียนและบริการสาธารณสุขสัตว์</label></div><button className="submit" disabled={saving}>{saving?'กำลังส่งข้อมูล…':'ยืนยันและส่งคำขอ →'}</button></form></main>}
    {view==='track'&&<main className="narrow"><button className="back" onClick={()=>setView('home')}>← กลับหน้าหลัก</button><div className="track-card"><div className="round-icon">⌕</div><p className="tag">ติดตามคำขอ</p><h1>ตรวจสอบสถานะการขึ้นทะเบียน</h1><p>กรอกเลขที่คำขอที่ได้รับหลังส่งข้อมูล</p><form onSubmit={track}><input value={reference} onChange={e=>setReference(e.target.value.toUpperCase())} placeholder="เช่น TSM-2569-100241" required/><button>ตรวจสอบ</button></form>{message&&<div className="error-box">{message}</div>}{tracking&&<div className="tracking"><span>เลขที่ {tracking.referenceNo}</span><b>{tracking.status==='APPROVED'?'อนุมัติแล้ว':'อยู่ระหว่างดำเนินการ'}</b><small>สถานะระบบ: {tracking.status}</small></div>}</div></main>}
    {view==='success'&&<main className="narrow"><div className="track-card success"><div className="check">✓</div><p className="tag">ส่งคำขอสำเร็จ</p><h1>เทศบาลได้รับข้อมูลแล้ว</h1><p>โปรดบันทึกเลขที่คำขอสำหรับติดตามผล</p><strong className="reference">{result?.referenceNo}</strong><button className="primary" onClick={()=>{setReference(result?.referenceNo||'');setView('track')}}>ติดตามคำขอนี้</button><button className="link" onClick={()=>{setForm(empty);setView('home')}}>กลับหน้าหลัก</button></div></main>}
    {view==='line'&&<main className="citizen-account"><button className="back" onClick={()=>setView('home')}>← กลับหน้าหลัก</button><div className="account-head"><div><p className="tag">LINE OA / LIFF</p><h1>สัตว์เลี้ยงและคำขอของฉัน</h1><p>ข้อมูลส่วนนี้เปิดได้เฉพาะเจ้าของที่ยืนยันตัวตนผ่าน LINE</p></div>{lineSession?.profile?.pictureUrl?<img src={lineSession.profile.pictureUrl} alt="โปรไฟล์ LINE"/>:null}</div>{message&&<div className="error-box">{message}</div>}{lineBusy?<div className="account-loading">กำลังเชื่อมต่อและตรวจสอบตัวตน…</div>:myData?.linked?<><section className="owner-card"><div><span>เจ้าของทะเบียน</span><b>{myData.owner.fullName}</b><small>บ้านเลขที่ {myData.owner.houseNo} หมู่ {myData.owner.villageNo} · {myData.owner.villageName}</small></div><strong>{myData.pets.length} ตัว</strong></section><section className="my-grid"><article><h2>สัตว์เลี้ยงของฉัน</h2>{myData.pets.length?myData.pets.map(pet=><div className="my-row" key={pet.id}><i>{pet.species==='DOG'?'ส':'ม'}</i><div><b>{pet.petName}</b><span>{pet.registrationNo||'อยู่ระหว่างขึ้นทะเบียน'} · {pet.status}</span><small>วัคซีนล่าสุด {pet.lastVaccinatedAt?new Date(pet.lastVaccinatedAt).toLocaleDateString('th-TH'):'ยังไม่มีข้อมูล'} · {Number(pet.sterilized)?'ทำหมันแล้ว':'ยังไม่ทำหมัน'}</small></div></div>):<p className="account-empty">ยังไม่มีสัตว์ในบัญชีนี้</p>}</article><article><h2>คำขอของฉัน</h2>{myData.registrations.length?myData.registrations.map(item=><div className="request-row" key={item.referenceNo}><div><b>{item.referenceNo}</b><span>{item.reviewNote||'ไม่มีหมายเหตุจากเจ้าหน้าที่'}</span></div><em>{REGISTRATION_STATUS_LABELS[item.status]||item.status}</em></div>):<p className="account-empty">ยังไม่มีคำขอ</p>}</article></section></>:citizenToken?<form className="link-owner-form" onSubmit={linkOwner}><h2>เชื่อมทะเบียนกับ LINE</h2><p>ใช้เลขคำขอและเบอร์โทรเดียวกับที่ยื่นไว้ เพื่อยืนยันว่าเป็นเจ้าของข้อมูล</p><label>เลขที่คำขอ<input value={linkForm.referenceNo} onChange={e=>setLinkForm({...linkForm,referenceNo:e.target.value.toUpperCase()})} placeholder="TSM-..." required/></label><label>หมายเลขโทรศัพท์<input value={linkForm.phone} onChange={e=>setLinkForm({...linkForm,phone:normalizeThaiPhone(e.target.value)})} inputMode="numeric" maxLength="10" required/></label><button className="submit" disabled={lineBusy}>ยืนยันและเชื่อมบัญชี</button></form>:<div className="line-connect"><h2>เข้าสู่ระบบด้วย LINE</h2><p>ระบบจะยืนยัน ID Token กับ LINE โดยตรง และไม่รับข้อมูลโปรไฟล์ที่ส่งจากหน้าเว็บ</p><button className="primary" onClick={openLine}>เชื่อมต่อ LINE</button></div>}</main>}
    <footer><b>{ORGANIZATION.shortName}</b><span>ระบบ PRMS-TSM · บริการประชาชนด้านสุขภาพสัตว์</span></footer></div>
}

const REGISTRATION_STATUS_LABELS={DRAFT:'แบบร่าง',SUBMITTED:'รอตรวจสอบ',UNDER_REVIEW:'กำลังตรวจ',NEED_MORE_INFO:'กรุณาแก้ไขข้อมูล',APPROVED:'อนุมัติแล้ว',REJECTED:'ไม่อนุมัติ'};

function Field({label,error,...props}){return <label>{label}<input {...props}/>{error&&<small>{error}</small>}</label>}
function FormSection({no,title,children}){return <section className="form-section"><div className="section-title"><i>{no}</i><h2>{title}</h2></div><div className="fields">{children}</div></section>}
