const names=["สมชาย ใจดี","มาลี พูนสุข","วิชัย แก้วดี","สุนิสา มีสุข","ประเสริฐ ทองแท้","นงลักษณ์ บุญมา","อนันต์ คำดี","จันทร์เพ็ญ ร่มเย็น","ธนวัฒน์ ศรีสุข","พิมพ์ใจ แสงทอง","สมคิด นาคงาม","กัลยา อยู่ดี","ณัฐวุฒิ แก้วใส","อรทัย ทองสุข","ประภาส คงมั่น","สุภาวดี ใจงาม","วิโรจน์ พันธุ์ดี","รัตนา มีศรี","ชัยวัฒน์ สุขใจ","พรทิพย์ แก้วคำ","มนัส ทองอยู่","วิภา รุ่งเรือง","อาคม บุญช่วย","สุดา แสงแก้ว","เกรียงไกร ใจตรง","อารีย์ พูนผล","สุชาติ รักดี","วาสนา งามพร้อม","บุญส่ง คำแหง","ปวีณา จันทร์ดี"];
const petNames=["เจ้าดำ","มะลิ","ถุงทอง","โกโก้","นำโชค","ข้าวปั้น","น้ำตาล","มีตังค์","ไข่ตุ๋น","ส้มจี๊ด","ข้าวเหนียว","ชาไทย","ลูกชิ้น","ปลาทู","ฟักทอง","แสนดี","บุญรอด","เปียกปูน","โอเลี้ยง","โมจิ","แพนด้า","ขนุน","ถั่วแดง","กะทิ","คุกกี้","พุดดิ้ง","ทองเอก","ดอลลี่","แจ่มใส","ตั้งใจ"];
const statuses=Array.from({length:30},(_,i)=>i<24?"APPROVED":i<27?"SUBMITTED":i<29?"UNDER_REVIEW":"REJECTED");
export const demoRegistrations=names.map((ownerName,i)=>({id:`demo-reg-${i+1}`,referenceNo:`TSM-2569-${100101+i}`,ownerName,petName:petNames[i],species:i%3===1?"CAT":"DOG",villageNo:(i%11)+1,status:statuses[i],submittedAt:`2026-07-${String(2+i%13).padStart(2,"0")}T${String(8+i%8).padStart(2,"0")}:30:00`}));
export const demoPets=demoRegistrations.filter(r=>r.status==="APPROVED").map((r,i)=>({id:`demo-pet-${i+1}`,registrationNo:`PET-2569-${String(i+1).padStart(4,"0")}`,petName:r.petName,species:r.species,sex:i%2?"FEMALE":"MALE",breed:r.species==="DOG"?["ไทยหลังอาน","พันธุ์ทาง","บางแก้ว","ชิสุ"][i%4]:["ไทย","วิเชียรมาศ","เปอร์เซีย"][i%3],color:["ดำ","ขาว–น้ำตาล","ลายเสือ","ส้ม","ขาว","เทา"][i%6],status:"ACTIVE",ownerName:r.ownerName,phone:`08${String(10000000+i*7919).slice(-8)}`,houseNo:String(18+(i*7)%190),villageNo:r.villageNo,lastVaccinatedAt:i<19?`2026-${String(2+i%5).padStart(2,"0")}-${String(5+i%20).padStart(2,"0")}`:null,sterilized:i%2===0}));
export const demoCases=[
  ["STRAY","พบสุนัขจรจัดรวมกลุ่มบริเวณตลาดช่วงเย็น","RECEIVED",3],["BITE","สุนัขกัดผู้ขับขี่รถจักรยานยนต์บริเวณทางเข้าหมู่บ้าน","IN_PROGRESS",5],["SICK","พบแมวมีอาการป่วยและไม่สามารถเดินได้","ASSIGNED",2],["NUISANCE","สุนัขเห่าส่งเสียงดังในช่วงกลางคืน","RESOLVED",8],["STRAY","ลูกสุนัขถูกทิ้งใกล้วัด จำนวน 4 ตัว","IN_PROGRESS",1],["OTHER","ขอให้ตรวจสอบสัตว์เลี้ยงที่ไม่มีผู้ดูแล","CLOSED",10],["BITE","ประชาชนขอคำแนะนำหลังสัมผัสสัตว์ต้องสงสัย","RECEIVED",6],["SICK","พบสุนัขมีบาดแผลบริเวณริมถนน","ASSIGNED",11],
].map((v,i)=>({id:`demo-case-${i+1}`,referenceNo:`CASE-2569-${501+i}`,category:v[0],description:v[1],status:v[2],villageNo:v[3],reporterName:names[20+i],createdAt:`2026-07-${String(8+i).padStart(2,"0")}T09:20:00`}));
export function demoReports(){return Array.from({length:11},(_,i)=>{const pets=demoPets.filter(p=>p.villageNo===i+1);return{villageNo:i+1,villageName:`หมู่ที่ ${i+1}`,totalPets:pets.length,dogs:pets.filter(p=>p.species==="DOG").length,cats:pets.filter(p=>p.species==="CAT").length,vaccinated:pets.filter(p=>p.lastVaccinatedAt).length,sterilized:pets.filter(p=>p.sterilized).length}})}
export function demoDashboard(){return{total:demoPets.length,dogs:demoPets.filter(p=>p.species==="DOG").length,cats:demoPets.filter(p=>p.species==="CAT").length,pending:demoRegistrations.filter(r=>["SUBMITTED","UNDER_REVIEW","NEED_MORE_INFO"].includes(r.status)).length,vaccinations:demoPets.filter(p=>p.lastVaccinatedAt).length,sterilizations:demoPets.filter(p=>p.sterilized).length,openCases:demoCases.filter(c=>!["RESOLVED","CLOSED"].includes(c.status)).length}}

export async function demoRequest(path,options={}){await new Promise(resolve=>setTimeout(resolve,100));const url=new URL(path,"https://demo.local");if(options.method==="PATCH"){const body=JSON.parse(options.body||"{}");const row=path.includes("/registrations/")?demoRegistrations.find(r=>path.includes(r.id)):demoCases.find(c=>path.includes(c.id));if(row&&body.status)row.status=body.status;return row||{status:body.status}}if(options.method==="POST")return{id:`demo-${Date.now()}`};if(path.startsWith("/api/admin/dashboard"))return demoDashboard();if(path.startsWith("/api/admin/registrations")){const status=url.searchParams.get("status");return status?demoRegistrations.filter(r=>r.status===status):demoRegistrations}if(path.startsWith("/api/admin/pets")){const q=(url.searchParams.get("search")||"").toLowerCase(),species=url.searchParams.get("species");return demoPets.filter(p=>(!species||p.species===species)&&(!q||[p.petName,p.ownerName,p.phone,p.registrationNo].some(v=>String(v).toLowerCase().includes(q))))}if(path==="/api/admin/cases")return demoCases;if(path==="/api/admin/reports/villages")return demoReports();throw new Error("ไม่พบข้อมูลสาธิต")}
