import { useEffect, useMemo, useState } from "react";
import { createApi } from "../../lib/api.js";
import { EmptyState, Notice, PageHead } from "../common/PageUI.jsx";

const thaiDate=value=>value?new Date(value).toLocaleDateString("th-TH",{day:"numeric",month:"short",year:"2-digit"}):"—";

function ServiceDialog({pet,api,onClose,onSaved}){const[type,setType]=useState("vaccine");const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[name,setName]=useState("วัคซีนป้องกันโรคพิษสุนัขบ้า");const[provider,setProvider]=useState("เทศบาลท่าโพธ์");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);async function save(e){e.preventDefault();setBusy(true);try{if(type==="vaccine")await api.post(`/api/admin/pets/${pet.id}/vaccinations`,{vaccineName:name,vaccinatedAt:date,providerName:provider,nextDueAt:"",lotNo:""});else await api.post(`/api/admin/pets/${pet.id}/sterilizations`,{sterilizedAt:date,providerName:provider,note:""});onSaved()}catch(err){setMessage(err.message)}finally{setBusy(false)}}return <div className="modal-backdrop"><form className="service-dialog" onSubmit={save}><div className="dialog-head"><div><p className="eyebrow">{pet.registrationNo}</p><h2>{pet.petName} · {pet.ownerName}</h2></div><button type="button" onClick={onClose}>×</button></div><label>ประเภทบริการ<select value={type} onChange={e=>setType(e.target.value)}><option value="vaccine">ฉีดวัคซีน</option><option value="sterilization">ทำหมัน</option></select></label>{type==="vaccine"&&<label>ชื่อวัคซีน<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>วันที่ให้บริการ<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>หน่วยบริการ<input value={provider} onChange={e=>setProvider(e.target.value)}/></label><Notice message={message}/><div className="dialog-actions"><button type="button" onClick={onClose}>ยกเลิก</button><button className="approve" disabled={busy}>{busy?"กำลังบันทึก…":"บันทึกประวัติ"}</button></div></form></div>}

export default function PetDirectory({token,serviceMode=false}){
  const api=useMemo(()=>createApi(token),[token]);const[rows,setRows]=useState([]);const[search,setSearch]=useState("");const[species,setSpecies]=useState("");const[selected,setSelected]=useState(null);const[message,setMessage]=useState("");
  const load=()=>api.get(`/api/admin/pets?search=${encodeURIComponent(search)}${species?`&species=${species}`:""}`).then(data=>setRows(Array.isArray(data)?data:[])).catch(e=>setMessage(e.message));
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[search,species,api]);
  return <><PageHead eyebrow={serviceMode?"งานบริการสัตวแพทย์":"ทะเบียนกลาง"} title={serviceMode?"บันทึกวัคซีนและทำหมัน":"ข้อมูลสัตว์ขึ้นทะเบียน"} detail={serviceMode?"บันทึกบริการเป็นประวัติรายครั้งและตรวจสอบย้อนหลังได้":"ค้นหาสัตว์ เจ้าของ เลขทะเบียน และสถานะสุขภาพ"} actions={<div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาชื่อ เจ้าของ โทรศัพท์…"/><select value={species} onChange={e=>setSpecies(e.target.value)}><option value="">ทุกชนิด</option><option value="DOG">สุนัข</option><option value="CAT">แมว</option></select></div>}/><Notice message={message}/><article className="panel module-panel">{!rows.length?<EmptyState text="ยังไม่มีสัตว์ที่ผ่านการขึ้นทะเบียน"/>:<div className="table-wrap"><table><thead><tr><th>สัตว์</th><th>เลขทะเบียน</th><th>เจ้าของ</th><th>ที่อยู่</th><th>วัคซีนล่าสุด</th><th>ทำหมัน</th>{serviceMode&&<th>บันทึกบริการ</th>}</tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><div className="pet-cell"><i>{p.species==="DOG"?"ส":"ม"}</i><span><b>{p.petName}</b><small>{p.species==="DOG"?"สุนัข":"แมว"} · {p.breed||"ไม่ระบุสายพันธุ์"}</small></span></div></td><td><b>{p.registrationNo||"รออนุมัติ"}</b></td><td>{p.ownerName}<small className="cell-sub">{p.phone}</small></td><td>{p.houseNo} หมู่ {p.villageNo}</td><td>{thaiDate(p.lastVaccinatedAt)}</td><td><span className={`badge ${p.sterilized?"green":"gray"}`}>{p.sterilized?"ทำแล้ว":"ยังไม่ทำ"}</span></td>{serviceMode&&<td><button className="service-btn" onClick={()=>setSelected(p)}>+ บันทึก</button></td>}</tr>)}</tbody></table></div>}</article>{selected&&<ServiceDialog pet={selected} api={api} onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);load()}}/>}</>;
}
